### ISSUE TITLE
438, 5, 'print "Library path ", LIBRARYPATH, "not found."\n'))

### ISSUE THREAD

**Issue by LaurentRouchairoles** [FreeCAD/FreeCAD-library#205]
I have a message : <unknown exception traceback><type 'exceptions.IndentationError'>: ('expected an indented block', ('/home/lolo/.FreeCAD/Macro/PartsLibrary.FCMacro', 438, 5, 'print "Library path ", LIBRARYPATH, "not found."\n')) 

[PartsLibrary.FCMacro.tar.gz](https://github.com/FreeCAD/FreeCAD-library/files/1194646/PartsLibrary.FCMacro.tar.gz)

The file is ./freecad/Macro I launch freecad but when I select the macro and select launch I have that message : <unknown exception traceback><type 'exceptions.IndentationError'>: ('expected an indented block', ('/home/lolo/.FreeCAD/Macro/PartsLibrary.FCMacro', 438, 5, 'print "Library path ", LIBRARYPATH, "not found."\n'))

I am running on a Vaio portable with linuxmint 18.2 cinamon 3.4.4 core linux 4.10.0-28 64bit system freecad is the stable version installed with ppa:freecad-maintainers/freecad-stable V16

**Comment by hyarion** [comment]
The issue seems to have been a missing indentation on the last line in the PartsLibrary.FCMacro file.
The strange thing is that the file never had that issue, I've checked the history of that particular line and it has been correctly indented for at least 7 years as far as I can tell.

My conclusion is that this must have been a user error. So for that reason, I think it is safe to close this issue.

**Comment by normandc** [comment]
It's more than 3 years old anyway, using the now prehistoric V0.16 version. V0.19 is due for release as soon as packagers resolve library issues, @LaurentRouchairoles please open a new issue if you still encounter the issue.
