### ISSUE TITLE
Broken Part in FreeCad 0.17

### ISSUE THREAD

**Issue by smithps** [FreeCAD/FreeCAD-library#227]
Hi, 'm looking at using the library of parts to model a Raspberry Pi. I have been playing around with various things and came across the parts library. The first part I picked was TQFP-144-IPC-MD.fcstd .... but I can't get it to draw in FreeCAD 0.17 

The item loads, but upon recalculation it complains about a while bunch of constraints and wants to use the Automatic Sketch fixing tool, which eventually just breaks everything. I can import the STEP file, but the FCStd file appears broken. 

Please advise if/how this can be resolved (I am a relative FreeCAD beginner, so don't know what to try next).

**Comment by Obijuan** [comment]
Hardly all the parts in the freecad library were designed with FreeCAD 0.16. There is a lot of work to do for migrating them to Freecad 0.17.  I've started to migrate a few of them. For example the through hole resistors: https://github.com/FreeCAD/FreeCAD-library/tree/master/Electrical%20Parts/electronic-components/resistors/through-hole

Any help will be very welcome :-)

**Comment by Obijuan** [comment]
The broken parts should be re-designed using FreeCAD 0.17. It is a good exercise for beginers: learn how the part has been designed and re-do it from scratch using FreeCAD 0.17. I am afraid that there is no procedure or process to follow to fix the broken parts. Just re-do them from scratch (but using the measures and data already available)

**Comment by ceremcem** [comment]
Isn't it important to use whether ASM2 or ASM3 (or any other method to make the assembly)?

**Comment by normandc** [comment]
Belated reply, but since Assembly2 and Assembly3 are external add-ons, I recommend not using them for the parts library; furthermore, Assembly3 requires a fork of FreeCAD made and maintained by its lone author, so it really should be avoided as long as his changes are not merged into the official FreeCAD source code.

**Comment by normandc** [comment]
@smithps, assuming you just need to use the component as is, the easy workaround as you yourself found is to import the STEP file rather than the original FCStd file. The STEP file imports as a "dumb" solid with no history.

If you want to modify this model, then unfortunately, you will need to repair the FCStd's features. You can get help on that on the FreeCAD forum, a helpful forum member may even be willing to do it for you.

Since this file is still unchanged for more than 2 years, and since this is an issue for a large number of files in the library, I'm closing this specific issue.
