### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by laguill** [FreeCAD/FreeCAD-library#427]
Hello,

I just discovered this project and it sounds pretty cool.

Would it be possible to add a search bar to look for a part ?

**Comment by yorikvanhavre** [comment]
The BIM library tool in the BIM workbench has a search bar. Although that tool is part of the BIM wb, it can be added and used in other workbenches too.

Note that there is a much larger project underway to redesign the whole library completely, and that will have a much better and proper tool in FreeCAD. https://forum.freecad.org/viewtopic.php?t=78124

I will close this issue because there is no further action required at this point, feel free to reopen if needed!

**Comment by tazztone** [comment]
is there a way to search for keywords of parts in freeCAD by now?
